networks:
  dev:

services:
  backend:
    build:
      context: "./backend"
    networks:
      dev:
    restart: unless-stopped
  
  frontend:
    build:
      context: "./frontend"
    ports:
      - "8501:8501"
    networks:
      dev:
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.43.0
    restart: unless-stopped
    networks:
      - dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus


volumes:
  prometheusdata: